In [15]:
import numpy as np

A = np.full( (3,3), 255 ) # Array With specific value 
print A

[[ 255.  255.  255.]
 [ 255.  255.  255.]
 [ 255.  255.  255.]]


In [16]:
A = np.full( (3,3), 255, dtype=np.uint8 ) # And specific type
print A

[[255 255 255]
 [255 255 255]
 [255 255 255]]


In [17]:
A = np.zeros( (2,2), dtype=np.uint8 )
print A

[[0 0]
 [0 0]]


In [21]:
e = np.random.random((2,2)) # random number [0,1]
print e

[[ 0.24815975  0.68325256]
 [ 0.72977344  0.17829313]]
